# Autogenerated with SMOP 
from smop.core import *
# matlab/aps_wrf_files_setup.m

    
    #     Copyright (C) 2015  Bekaert David - University of Leeds
#     Email: eedpsb@leeds.ac.uk or davidbekaert.com
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License along
#     with this program; if not, write to the Free Software Foundation, Inc.,
#     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
    
    # By Bekaert David -- University of Leeds
    
    # modifications 
# 12/2013 	DB 	Include support for GFSR data
# 12/2013   DB  Add an additional datafile for GFSR such the first time
#               stamp is found. 
# 04/2014   DB  Fixed error in file definition for end of december dates
    
    # Set up the WRF data directory structure
    wrf_datapath=matlabarray([])
# matlab/aps_wrf_files_setup.m:30
    
    # getting the variables from the parms_aps file
    stamps_processed=getparm_aps('stamps_processed')
# matlab/aps_wrf_files_setup.m:33
    ll_matfile=getparm_aps('ll_matfile')
# matlab/aps_wrf_files_setup.m:34
    UTC_sat=getparm_aps('UTC_sat')
# matlab/aps_wrf_files_setup.m:35
    t_spin_up='12:00'
# matlab/aps_wrf_files_setup.m:36
    
    data_intervals=6
# matlab/aps_wrf_files_setup.m:37
    
    if isempty(wrf_datapath):
        wrf_datapath=getparm_aps('wrf_datapath')
# matlab/aps_wrf_files_setup.m:40
    
    
    # loading the data
    if strcmp(stamps_processed,'y'):
        ps=load(ll_matfile)
# matlab/aps_wrf_files_setup.m:45
        dates=ps.day
# matlab/aps_wrf_files_setup.m:46
        load('psver')
        fprintf('Stamps processed structure \\n')
    else:
        psver=2
# matlab/aps_wrf_files_setup.m:50
        ifgday_matfile=getparm_aps('ifgday_matfile')
# matlab/aps_wrf_files_setup.m:51
        ifgs_dates=load(ifgday_matfile)
# matlab/aps_wrf_files_setup.m:52
        ifgs_dates=ifgs_dates.ifgday
# matlab/aps_wrf_files_setup.m:53
        dates=reshape(ifgs_dates,[],1)
# matlab/aps_wrf_files_setup.m:54
        dates=unique(dates)
# matlab/aps_wrf_files_setup.m:55
        dates=datenum(num2str(dates),'yyyymmdd')
# matlab/aps_wrf_files_setup.m:56
    
    t_SAR=str2num(UTC_sat[1:2]) + str2num(UTC_sat[4:5]) / 60
# matlab/aps_wrf_files_setup.m:58
    t_spin=str2num(t_spin_up[1:2]) + str2num(t_spin_up[4:5]) / 60
# matlab/aps_wrf_files_setup.m:59
    # add another time shift to include GFSR data such the full spin up time
# can be completed. Otherzise the first time stamp will not be found.
    t_spin=t_spin + data_intervals
# matlab/aps_wrf_files_setup.m:62
    t_start=t_SAR - t_spin
# matlab/aps_wrf_files_setup.m:63
    # getting the start date of the model
    if t_start < 0:
        n_days=floor(t_start / 24)
# matlab/aps_wrf_files_setup.m:67
        dates_model=dates - abs(n_days)
# matlab/aps_wrf_files_setup.m:68
        time_model=abs(dot(n_days,24)) - abs(t_start)
# matlab/aps_wrf_files_setup.m:69
    else:
        n_days=0
# matlab/aps_wrf_files_setup.m:71
        dates_model=copy(dates)
# matlab/aps_wrf_files_setup.m:72
        time_model=copy(t_start)
# matlab/aps_wrf_files_setup.m:73
    
    # gettign the start time of the model
    time_model_ix=floor(time_model / data_intervals)
# matlab/aps_wrf_files_setup.m:76
    time_model=dot(time_model_ix,data_intervals)
# matlab/aps_wrf_files_setup.m:77
    time_model=num2str(time_model)
# matlab/aps_wrf_files_setup.m:78
    if length(time_model) == 1:
        time_model=matlabarray(cat('0',time_model))
# matlab/aps_wrf_files_setup.m:80
    
    # getting the last required time of model data
    time_model_end=dot(ceil(t_SAR / data_intervals),data_intervals)
# matlab/aps_wrf_files_setup.m:84
    dates_model_end=copy(dates)
# matlab/aps_wrf_files_setup.m:85
    if time_model_end == 24:
        time_model_end=0
# matlab/aps_wrf_files_setup.m:87
        dates_model_end=dates_model_end + 1
# matlab/aps_wrf_files_setup.m:88
    
    time_model_end=num2str(time_model_end)
# matlab/aps_wrf_files_setup.m:90
    if length(time_model_end) == 1:
        time_model_end=matlabarray(cat('0',time_model_end))
# matlab/aps_wrf_files_setup.m:92
    
    # Download data for the period:
    GDAS_flag=0
# matlab/aps_wrf_files_setup.m:97
    GFS_flag=0
# matlab/aps_wrf_files_setup.m:98
    data_filename_GDAS_prev=matlabarray([])
# matlab/aps_wrf_files_setup.m:99
    data_filename_GDAS_prev2=matlabarray([])
# matlab/aps_wrf_files_setup.m:100
    # Download data for the period:
    for k in arange(1,length(dates)).reshape(-1):
        # getting the model run times in days, hours minutes, seconds
        n_run_days=datenum(cat(datestr(dates_model_end[k],'yyyymmdd'),'_',time_model_end,'0000'),'yyyymmdd_HHMMSS') - datenum(cat(datestr(dates_model[k],'yyyymmdd'),'_',time_model,'0000'),'yyyymmdd_HHMMSS')
# matlab/aps_wrf_files_setup.m:105
        n_run_days_int=floor(n_run_days)
# matlab/aps_wrf_files_setup.m:106
        n_run_hours=dot((n_run_days - n_run_days_int),24)
# matlab/aps_wrf_files_setup.m:107
        n_run_hours_int=floor(n_run_hours)
# matlab/aps_wrf_files_setup.m:108
        n_run_minutes=dot((n_run_hours - n_run_hours_int),60)
# matlab/aps_wrf_files_setup.m:109
        n_run_minutes_int=floor(n_run_minutes)
# matlab/aps_wrf_files_setup.m:110
        n_run_seconds=round(dot((n_run_minutes - n_run_minutes_int),60))
# matlab/aps_wrf_files_setup.m:111
        start_time=datenum(cat(datestr(dates_model[k],'yyyymmdd'),'_',time_model,'0000'),'yyyymmdd_HHMMSS')
# matlab/aps_wrf_files_setup.m:114
        end_time=datenum(cat(datestr(dates_model_end[k],'yyyymmdd'),'_',time_model_end,'0000'),'yyyymmdd_HHMMSS')
# matlab/aps_wrf_files_setup.m:115
        n_datafiles=dot((end_time - start_time),24) / data_intervals + 1
# matlab/aps_wrf_files_setup.m:117
        for kk in arange(1,n_datafiles).reshape(-1):
            data_time=start_time + dot((kk - 1),data_intervals) / 24
# matlab/aps_wrf_files_setup.m:120
            data_time_str=datestr(data_time,'yyyymmdd_HHMM')
# matlab/aps_wrf_files_setup.m:121
            if exist(cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files'),'dir') != 7:
                mkdir(cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files'))
            # GFSR
            GFSR_check=datenum(datestr(data_time,'yyyymmdd'),'yyyymmdd') - datenum('20061101','yyyymmdd')
# matlab/aps_wrf_files_setup.m:130
            if GFSR_check < 0 and GDAS_flag == 0:
                GDAS_flag=1
# matlab/aps_wrf_files_setup.m:132
                mkdir(cat(wrf_datapath,filesep,'temp'))
            else:
                if GFSR_check >= 0 and GFS_flag == 0:
                    GFS_flag=1
# matlab/aps_wrf_files_setup.m:135
            # checking if the GFS file exists otherwize use GDAS files
            if GFSR_check < 0:
                # For GFSR an extra time stamp is needed. 
             # This is not required for GFS data
                skip_flag=0
# matlab/aps_wrf_files_setup.m:142
                ix_file_number=ceil(str2num(data_time_str[7:8]) / 5)
# matlab/aps_wrf_files_setup.m:143
                if ix_file_number == 1:
                    filestr=matlabarray(cat(data_time_str[1:6],'01-',data_time_str[1:6],'05'))
# matlab/aps_wrf_files_setup.m:145
                else:
                    if ix_file_number == 2:
                        filestr=matlabarray(cat(data_time_str[1:6],'06-',data_time_str[1:6],'10'))
# matlab/aps_wrf_files_setup.m:147
                    else:
                        if ix_file_number == 3:
                            filestr=matlabarray(cat(data_time_str[1:6],'11-',data_time_str[1:6],'15'))
# matlab/aps_wrf_files_setup.m:149
                        else:
                            if ix_file_number == 4:
                                filestr=matlabarray(cat(data_time_str[1:6],'16-',data_time_str[1:6],'20'))
# matlab/aps_wrf_files_setup.m:151
                            else:
                                if ix_file_number == 5:
                                    filestr=matlabarray(cat(data_time_str[1:6],'21-',data_time_str[1:6],'25'))
# matlab/aps_wrf_files_setup.m:153
                                else:
                                    if ix_file_number >= 6:
                                        # get the end day of the month
                                        dummy_month=num2str(str2num(data_time_str[5:6]) + 1)
# matlab/aps_wrf_files_setup.m:156
                                        data_time_end_temp=str2num(data_time_str[1:4])
# matlab/aps_wrf_files_setup.m:157
                                        if str2num(dummy_month) > 12:
                                            dummy_month='1'
# matlab/aps_wrf_files_setup.m:160
                                            data_time_end_temp=data_time_end_temp + 1
# matlab/aps_wrf_files_setup.m:161
                                        data_time_end_temp=num2str(data_time_end_temp)
# matlab/aps_wrf_files_setup.m:163
                                        if length(dummy_month) == 1:
                                            dummy_month=matlabarray(cat('0',dummy_month))
# matlab/aps_wrf_files_setup.m:166
                                        end_day_month=datestr(datenum(cat(data_time_end_temp,dummy_month,'01'),'yyyymmdd') - 1,'dd')
# matlab/aps_wrf_files_setup.m:168
                                        filestr=matlabarray(cat(data_time_str[1:6],'26-',data_time_str[1:6],end_day_month))
# matlab/aps_wrf_files_setup.m:169
                data_filename_GDAS=matlabarray(cat(datestr(dates[k],'yyyy'),filesep,'pgbh06.gdas.',filestr,'.tar \\n'))
# matlab/aps_wrf_files_setup.m:171
                data_filename_GDAS2=matlabarray(cat(datestr(dates[k],'yyyy'),filesep,'flxf06.gdas.',filestr,'.tar \\n'))
# matlab/aps_wrf_files_setup.m:172
                if exist(cat(wrf_datapath,filesep,'temp'),'file') == 2:
                    fprintf('There is a file called temp, delete it first otherwize you will loose the downloaded files when performing untar \\n')
                    keyboard
                # zip file contains multiple dates only take those that
             # have not been taken yet.
                if strcmp(data_filename_GDAS,data_filename_GDAS_prev) != 1:
                    data_filename_GDAS_prev=copy(data_filename_GDAS)
# matlab/aps_wrf_files_setup.m:184
                    if exist(cat(wrf_datapath,filesep,data_filename_GDAS[6:end() - 3])):
                        command_str=matlabarray(cat('tar -xvf ',wrf_datapath,filesep,data_filename_GDAS[6:end() - 2],' -C ',wrf_datapath,filesep,'temp'))
# matlab/aps_wrf_files_setup.m:186
                        status,cmdout=system(command_str,nargout=2)
# matlab/aps_wrf_files_setup.m:187
                        movefile(cat(wrf_datapath,filesep,data_filename_GDAS[6:end() - 3]),cat(wrf_datapath,filesep,'temp',filesep,'.'))
                        command_str2=matlabarray(cat('tar -xvf ',wrf_datapath,filesep,data_filename_GDAS2[6:end() - 2],' -C ',wrf_datapath,filesep,'temp'))
# matlab/aps_wrf_files_setup.m:189
                        status,cmdout=system(command_str2,nargout=2)
# matlab/aps_wrf_files_setup.m:190
                        if exist(cat(wrf_datapath,filesep,data_filename_GDAS2[6:end() - 3]),'file') == 2:
                            movefile(cat(wrf_datapath,filesep,data_filename_GDAS2[6:end() - 3]),cat(wrf_datapath,filesep,'temp',filesep,'.'))
                if strcmp(data_filename_GDAS2,data_filename_GDAS_prev2) != 1:
                    data_filename_GDAS_prev2=copy(data_filename_GDAS2)
# matlab/aps_wrf_files_setup.m:197
                    if exist(cat(wrf_datapath,filesep,data_filename_GDAS2[6:end() - 3])):
                        command_str2=matlabarray(cat('tar -xvf ',wrf_datapath,filesep,data_filename_GDAS2[6:end() - 2],' -C ',wrf_datapath,filesep,'temp'))
# matlab/aps_wrf_files_setup.m:199
                        status,cmdout=system(command_str2,nargout=2)
# matlab/aps_wrf_files_setup.m:200
                        if exist(cat(wrf_datapath,filesep,data_filename_GDAS2[6:end() - 3]),'file') == 2:
                            movefile(cat(wrf_datapath,filesep,data_filename_GDAS2[6:end() - 3]),cat(wrf_datapath,filesep,'temp',filesep,'.'))
                data_time_str_new=datestr(datenum(data_time_str[1:end() - 2],'yyyymmdd_HH'),'yyyymmddHH')
# matlab/aps_wrf_files_setup.m:206
                if exist(cat(wrf_datapath,filesep,'temp',filesep,'pgbh06.gdas.',data_time_str_new,'.grb2')):
                    if exist(cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'pressure'),'dir') != 7:
                        mkdir(cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'pressure'))
                    if exist(cat(wrf_datapath,filesep,'temp',filesep,'pgbh06.gdas.',data_time_str_new,'.grb2'),'file') == 2:
                        movefile(cat(wrf_datapath,filesep,'temp',filesep,'pgbh06.gdas.',data_time_str_new,'.grb2'),cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'pressure',filesep,'pgbh06.gdas.',data_time_str_new,'.grb2'))
                if exist(cat(wrf_datapath,filesep,'temp',filesep,'flxf06.gdas.',data_time_str_new,'.grb2')):
                    if exist(cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'surface'),'dir') != 7:
                        mkdir(cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'surface'))
                    if exist(cat(wrf_datapath,filesep,'temp',filesep,'flxf06.gdas.',data_time_str_new,'.grb2'),'file') == 2:
                        movefile(cat(wrf_datapath,filesep,'temp',filesep,'flxf06.gdas.',data_time_str_new,'.grb2'),cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'surface',filesep,'flxf06.gdas.',data_time_str_new,'.grb2'))
                clear('filestr','data_filename_GDAS')
            else:
                # GFS file should exist 
            # For GFSR an extra time stamp is needed. 
            # This is not required for GFS data
                if kk > 1:
                    skip_flag=0
# matlab/aps_wrf_files_setup.m:231
                else:
                    skip_flag=1
# matlab/aps_wrf_files_setup.m:233
                if skip_flag == 0:
                    if exist(cat(wrf_datapath,filesep,'GFS_Global_0p5deg_',data_time_str,'_anl.grib2')):
                        movefile(cat(wrf_datapath,filesep,'GFS_Global_0p5deg_',data_time_str,'_anl.grib2'),cat(wrf_datapath,filesep,datestr(dates[k],'yyyymmdd'),filesep,'files',filesep,'GFS_Global_0p5deg_',data_time_str,'_anl.grib2'))
    
    