# Autogenerated with SMOP 
from smop.core import *
# Trainmatlab.v.0/resampling_radar_coor.m

    
@function
def resampling_radar_coor(multi_look_range=None,phase_in=None,ps=None,*args,**kwargs):
    varargin = resampling_radar_coor.varargin
    nargin = resampling_radar_coor.nargin

    # Multi-look inputted data based on the radar coordiantes and and the
# multi-look factor for the range direction. The azimuth direction follows
# based on the aspect ratio. As output the multi-looked data is given
# together with a the new positions XY in a local frame and the radar
# coordinates IJ.
# 
#     Copyright (C) 2015  Bekaert David - University of Leeds
#     Email: eedpsb@leeds.ac.uk or davidbekaert.com
# 
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License along
#     with this program; if not, write to the Free Software Foundation, Inc.,
#     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
    
    # Bekaert David
    
    if nargin < 1:
        multi_look_range=20
# Trainmatlab.v.0/resampling_radar_coor.m:30
    
    ar=ps.ar
# Trainmatlab.v.0/resampling_radar_coor.m:33
    ps.ij_new = copy(ps.ij)
# Trainmatlab.v.0/resampling_radar_coor.m:34
    ps.ij_new[:,3]=ceil(dot(ps.ij(arange(),3) / max(ps.ij(arange(),3)),multi_look_range))
# Trainmatlab.v.0/resampling_radar_coor.m:35
    ps.ij_new[:,2]=ceil(dot(ps.ij(arange(),2) / ar / max(ps.ij(arange(),3)),multi_look_range))
# Trainmatlab.v.0/resampling_radar_coor.m:36
    ij=NaN(cat(1,3))
# Trainmatlab.v.0/resampling_radar_coor.m:39
    xy=NaN(cat(1,3))
# Trainmatlab.v.0/resampling_radar_coor.m:40
    lonlat=NaN(cat(1,2))
# Trainmatlab.v.0/resampling_radar_coor.m:41
    phase=NaN(cat(1,size(phase_in,2)))
# Trainmatlab.v.0/resampling_radar_coor.m:42
    counter=1
# Trainmatlab.v.0/resampling_radar_coor.m:45
    n_grid=dot(max(ps.ij_new(arange(),2)),max(ps.ij_new(arange(),3)))
# Trainmatlab.v.0/resampling_radar_coor.m:46
    h=waitbar(0,'Resampling data, Please wait...')
# Trainmatlab.v.0/resampling_radar_coor.m:47
    for i in arange(1,max(ps.ij_new(arange(),2))).reshape(-1):
        for k in arange(1,max(ps.ij_new(arange(),3))).reshape(-1):
            ix=find(ps.ij_new(arange(),2) == logical_and(i,ps.ij_new(arange(),3)) == k)
# Trainmatlab.v.0/resampling_radar_coor.m:51
            if isempty(ix) != 1:
                ij[counter,1]=counter
# Trainmatlab.v.0/resampling_radar_coor.m:53
                xy[counter,1]=counter
# Trainmatlab.v.0/resampling_radar_coor.m:54
                ij[counter,2:3]=cat(i,k)
# Trainmatlab.v.0/resampling_radar_coor.m:55
                xy[counter,2:3]=mean(ps.xy(ix,arange(2,3)),1)
# Trainmatlab.v.0/resampling_radar_coor.m:56
                lonlat[counter,1:2]=mean(ps.lonlat(ix,arange()),1)
# Trainmatlab.v.0/resampling_radar_coor.m:57
                A=ones(cat(size(ix,1),1))
# Trainmatlab.v.0/resampling_radar_coor.m:60
                phase[counter,:]=lscov(A,phase_in[ix,:])
# Trainmatlab.v.0/resampling_radar_coor.m:61
                counter=counter + 1
# Trainmatlab.v.0/resampling_radar_coor.m:64
                waitbar(counter / n_grid)
    
    close_(h)
    # reconstruct the matrix in radar coordiantes
    phase_matrix=NaN(cat(max(ij[:,2:3]),size(phase_in,2)))
# Trainmatlab.v.0/resampling_radar_coor.m:73
    for k in arange(1,ij[end(),1]).reshape(-1):
        phase_matrix[ij[k,2],ij[k,3],:]=phase[k,:]
# Trainmatlab.v.0/resampling_radar_coor.m:76
    
    bperp=ps.bperp
# Trainmatlab.v.0/resampling_radar_coor.m:80
    day=ps.day
# Trainmatlab.v.0/resampling_radar_coor.m:81
    day_ix=ps.day_ix
# Trainmatlab.v.0/resampling_radar_coor.m:82
    master_day=ps.master_day
# Trainmatlab.v.0/resampling_radar_coor.m:83
    master_ix=ps.master_ix
# Trainmatlab.v.0/resampling_radar_coor.m:84
    n_ifg=ps.n_ifg
# Trainmatlab.v.0/resampling_radar_coor.m:85
    n_image=ps.n_image
# Trainmatlab.v.0/resampling_radar_coor.m:86
    n_ps=size(lonlat,1)
# Trainmatlab.v.0/resampling_radar_coor.m:87